{% set name = "openmesh-python" %}
{% set pypiname = "openmesh" %}
{% set version = "1.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: cd1c4286ab22b9d50e403c9669e94e41dedc59020d76e069b9b4013066865e2e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
    - setuptools_scm
    - numpy
    - pybind11
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - openmesh
  source_files:
    - tests
  commands:
    - cd tests
    - python -m unittest discover

about:
  home: https://www.graphics.rwth-aachen.de:9000/OpenMesh/openmesh-python
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OpenMesh Python Bindings

  description: |
    OpenMesh is a versatile halfedge-based data structure for representing
    and manipulating polygon meshes.
    The OpenMesh Python bindings are are tightly integrated with numpy and
    are implemented using pybind11.
  doc_url: https://openmesh-python.readthedocs.io/en/latest/
  dev_url: https://www.graphics.rwth-aachen.de:9000/OpenMesh/openmesh-python

extra:
  recipe-maintainers:
    - mdraw
