{% set name = "openmesh-python" %}
{% set pypiname = "openmesh" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: 6fd3fa41a68148e4a7523f562426aa9758bf65ccc6642abcf79c37bae9c6af3c

build:
  skip: true  # [win and py>39]  # TODO: Fix issue with undefined ssize_t and re-enable build
  number: 5
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
  host:
    - python
    - pip
    - setuptools_scm
    - numpy
    - pybind11
  run:
    - python

test:
  imports:
    - openmesh
  source_files:
    - tests
  commands:
    - cd tests
    - python -m unittest discover

about:
  home: https://www.graphics.rwth-aachen.de:9000/OpenMesh/openmesh-python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OpenMesh Python Bindings

  description: |
    OpenMesh is a versatile halfedge-based data structure for representing
    and manipulating polygon meshes.
    The OpenMesh Python bindings are are tightly integrated with numpy and
    are implemented using pybind11.
  doc_url: https://openmesh-python.readthedocs.io/en/latest/
  dev_url: https://www.graphics.rwth-aachen.de:9000/OpenMesh/openmesh-python

extra:
  recipe-maintainers:
    - stuarteberg
    - mdraw
